# Generated by Django 3.0.2 on 2020-05-17 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moreImages', models.ImageField(blank=True, null=True, upload_to='image/events/moreImages')),
            ],
        ),
        migrations.RemoveField(
            model_name='events',
            name='id',
        ),
        migrations.AddField(
            model_name='events',
            name='date',
            field=models.DateField(default='2019-02-02', help_text='Please use the following format: <em>YYYY-MM-DD</em>.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='events',
            name='description',
            field=models.TextField(default='hello'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='events',
            name='details',
            field=models.TextField(default='gg'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='events',
            name='imageTop',
            field=models.ImageField(blank=True, null=True, upload_to='image/events/imageTop'),
        ),
        migrations.AlterField(
            model_name='events',
            name='title',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='events',
            name='moreImages',
            field=models.ManyToManyField(to='bbapp.EventImages'),
        ),
    ]
