# Generated by Django 3.0.2 on 2020-05-17 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bbapp', '0003_auto_20200518_0109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='moreImages',
        ),
        migrations.AddField(
            model_name='eventimages',
            name='title',
            field=models.ForeignKey(default='hello', on_delete=django.db.models.deletion.CASCADE, to='bbapp.Events'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eventimages',
            name='moreImages',
            field=models.ImageField(blank=True, null=True, upload_to='image/events/moreImages'),
        ),
    ]
