# Generated by Django 3.0.2 on 2020-05-17 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bbapp', '0004_auto_20200518_0119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventimages',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bbapp.Events'),
        ),
    ]
