# Generated by Django 3.0.2 on 2020-05-17 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bbapp', '0005_auto_20200518_0122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventimages',
            name='moreImages',
            field=models.ImageField(blank=True, null=True, upload_to='images/events/moreImages'),
        ),
        migrations.AlterField(
            model_name='eventimages',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bbapp.Events'),
        ),
    ]
