# Generated by Django 3.0.2 on 2020-05-18 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bbapp', '0007_auto_20200518_0125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventimages',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moreImages', to='bbapp.Events'),
        ),
    ]
